#!groovy

timeout(time: 60, unit: 'MINUTES'){
	node {
	
	// Wait until authorization to push to production
    stage('Approve QA Deployment') {
        timeout(time: 2, unit: 'DAYS') {
            input message: 'Do you want to deploy into QA?'
        }
    }
	
	stage("Choose Version") {
		sh "oc project dev"
        env.version = selectVersion("parking-api", "dev-", "dev");
    }
	
    // Publish to a QA environment
    stage('Deploy to QA') {
		sh "oc project test"
		openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'parking-api', destTag: "qa-${version}", destinationAuthToken: '', destinationNamespace: 'dev', namespace: 'dev', srcStream: 'parking-api', srcTag: "dev-${version}", verbose: 'false'
		sh "oc patch dc parking-api-qa --patch '{"spec": { "triggers": [ { "type": "ImageChange", "imageChangeParams": { "containerNames": [ "parking-api-qa" ], "from": { "kind": "ImageStreamTag", "namespace": "dev", "name": "parking-api:qa-${version}"}}}]}}' -n test"
        openshiftDeploy apiURL: '', authToken: '', depCfg: 'parking-api-qa', namespace: 'test', verbose: 'false', waitTime: ''
        openshiftVerifyDeployment apiURL: '', authToken: '', depCfg: 'parking-api-qa', namespace: 'test', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: ''

        openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'parking-api', destTag: "prod-$version", destinationAuthToken: '', destinationNamespace: 'dev', namespace: 'dev', srcStream: 'parking-api', srcTag: "qa-$version", verbose: 'false'
    }
    // Wait until authorization to push to production
    stage('Approve Production Deployment') {
        timeout(time: 2, unit: 'DAYS') {
            input message: 'Do you want to deploy into production?'
        }
    }
    // Push to production
    stage('Deploy to Production') {
		sh "oc project prod"
		sh "oc patch dc api-green --patch '{\"spec\": { \"triggers\": [ { \"type\": \"ImageChange\", \"imageChangeParams\": { \"containerNames\": [ \"api-green\" ], \"from\": { \"kind\": \"ImageStreamTag\", \"namespace\": \"dev\", \"name\": \"parking-api:prod-$version\"}}}]}}' -n prod"
        openshiftDeploy apiURL: '', authToken: '', depCfg: "api-green", namespace: 'prod', verbose: 'false', waitTime: ''
        openshiftVerifyDeployment apiURL: '', authToken: '', depCfg: "api-green" , namespace: 'prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: ''
    }
	}
}

def selectVersion(imageName, tagPrefix, namespace) {
		def selectedTag = ""
		sh "oc get istag -n ${namespace} --sort-by='{.metadata.name}'| grep ${imageName}| grep ${tagPrefix} | awk '{print \$1}' | awk -F ':' '{print \$2}' | awk -F '-' '{print \$2}' | tail -5 > tags"
		def tags = readFile("tags").trim()
		echo tags
		selectedTag = input message: "Choose version",
            parameters: [choice(choices: tags, description: '', name: 'Versions')]

		return selectedTag
}
